import '../contacts/contacts.graphql'
import '../tags/tags.graphql'
import '../segments/segments.graphql'
import '../users/users.graphql'
import '../roles/roles.graphql'
import '../permissions/permissions.graphql'
import '../teams/teams.graphql'
import '../sharing/sharing.graphql'
import '../audit/audit.graphql'
import '../auth/api-key.graphql'
import '../inbox/inbox.graphql'
import '../facebook/facebook.graphql'
import '../products/products.graphql'
import '../competitors/competitors.graphql'
import '../deal-collaboration/deal-collaboration.graphql'
import '../deal-health/deal-health.graphql'
import '../tasks/tasks.graphql'
import '../reports/reports.graphql'
import { builder } from './schema.builder'

export const schema = builder.toSchema({})
